apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service-deployment
  labels:
    app: shipping
spec:
  selector:
    matchLabels:
      app: shipping
  replicas: 1
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: webper2606/swa-project2:shipping-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: accountservice
              valueFrom:
                configMapKeyRef:
                  name: shipping-config
                  key: accountservice
            - name: bankaccountservice
              valueFrom:
                configMapKeyRef:
                  name: shipping-config
                  key: bankaccountservice
            - name: creditservice
              valueFrom:
                configMapKeyRef:
                  name: shipping-config
                  key: creditservice
            - name: orderservice
              valueFrom:
                configMapKeyRef:
                  name: shipping-config
                  key: orderservice
            - name: paymentservice
              valueFrom:
                configMapKeyRef:
                  name: shipping-config
                  key: paymentservice
            - name: paypalservice
              valueFrom:
                configMapKeyRef:
                  name: shipping-config
                  key: paypalservice
            - name: productservice
              valueFrom:
                configMapKeyRef:
                  name: shipping-config
                  key: productservice
            - name: shippingservice
              valueFrom:
                configMapKeyRef:
                  name: shipping-config
                  key: shippingservice
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: shipping-config
                  key: dbUrl
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: productdb-config
                  key: dbName
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: productdb-secrets
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: productdb-secrets
                  key: password
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://$(DB_URL)/$(DB_NAME)?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
---
kind: Service
apiVersion: v1
metadata:
  name: shipping-service
spec:
  selector:
    app: shipping
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
data:
  dbUrl: product-db-service
  accountservice: http://account-service:8080
  bankaccountservice: http://bank-account-service:8080
  creditservice: http://credit-service:8080
  orderservice: http://order-service:8080
  paymentservice: http://payment-service:8080
  paypalservice: http://paypal-service:8080
  productservice: http://product-service:8080
  shippingservice: http://shipping-service:8080
