apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shipping-service-db-volume
  labels:
    app: shippingdb-volume
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service-db-deployment
  labels:
    app: shippingdb
    tier: database
spec:
  selector:
    matchLabels:
      app: shippingdb
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: shippingdb
        tier: database
    spec:
      containers:
        - image: mysql
          name: shippingdb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shippingdb-secrets
                  key: password

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: shippingdb-config
                  key: dbName
          ports:
            - containerPort: 3306
              name: shippingdb
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: shipping-service-db-volume
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-db-service
spec:
  type: NodePort
  selector:
    app: shippingdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shippingdb-config
data:
  dbName: shippingdb
---
apiVersion: v1
kind: Secret
metadata:
  name: shippingdb-secrets
data:
  username: cm9vdA==
  password: c2EyMDIy
