apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: estore-ingress
  namespace: default
spec:
  rules:
    - host: a.uz
      http:
        paths:
          - path: /accounts
            pathType: Prefix
            backend:
              service:
                name: account-service
                port:
                  number: 8080
          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 8080
          - path: /shipping
            pathType: Prefix
            backend:
              service:
                name: shipping-service
                port:
                  number: 8080
          - path: /product
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 8080
          - path: /paypal
            pathType: Prefix
            backend:
              service:
                name: paypal-service
                port:
                  number: 8080
          - path: /bankaccount
            pathType: Prefix
            backend:
              service:
                name: bank-account-service
                port:
                  number: 8080
          - path: /credit
            pathType: Prefix
            backend:
              service:
                name: credit-service
                port:
                  number: 8080
          - path: /payment
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 8080
