apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
  labels:
    app: account
spec:
  selector:
    matchLabels:
      app: account
  replicas: 2
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: webper2606/swa-project2:account-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: account-config
                  key: dbUrl
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: account-config
                  key: dbName
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: account-secrets
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: account-secrets
                  key: password
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://$(DB_URL)/$(DB_NAME)?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
---
kind: Service
apiVersion: v1
metadata:
  name: account-service
spec:
  selector:
    app: account
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: account-config
data:
  dbUrl: account-db-service
  dbName: accountdb
---
apiVersion: v1
kind: Secret
metadata:
  name: account-secrets
data:
  username: cm9vdA==
  password: c2EyMDIy
