server:
  port: 8082
spring:
  application:
    name: bank-account-service
accountservice: http://localhost:8081
bankaccountservice: http://localhost:8082
creditservice: http://localhost:8083
orderservice: http://localhost:8084
paymentservice: http://localhost:8085
paypalservice: http://localhost:8086
productservice: http://localhost:8087
shippingservice: http://localhost:8088
app:
  jwt:
    jwtSecret: AAAATQAAAHkAAABTAAAAZQAAAGMAAAByAAAAZQAAAHQAAABLAAAAZQAAAHk=