apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  labels:
    app: product
spec:
  selector:
    matchLabels:
      app: product
  replicas: 1
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: webper2606/swa-project2:product-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: ACCOUNT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: account_service
            - name: BANK_ACCOUNT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: bank_account_service
            - name: CREDIT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: credit_service
            - name: ORDER_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: order_service
            - name: PAYMENT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: payment_service
            - name: PAYPAL_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: paypal_service
            - name: PRODUCT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: product_service
            - name: SHIPPING_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: shipping_service
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: dbUrl
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: productdb-config
                  key: dbName
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: productdb-secrets
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: productdb-secrets
                  key: password
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://$(DB_URL)/$(DB_NAME)?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
---
kind: Service
apiVersion: v1
metadata:
  name: product-service
spec:
  selector:
    app: product
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
data:
  dbUrl: product-db-service
  account_service: account-service
  bank_account_service: bank-account-service
  credit_service: credit-service
  order_service: order-service
  payment_service: payment-service
  paypal_service: paypal-service
  product_service: product-service
  shipping_service: shipping-service
