server:
  port: 8084
spring:  
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/orderservice?createDatabaseIfNotExist=true
    username: root
    password: e123123A!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
accountservice: http://localhost:8081
bankaccountservice: http://localhost:8082
creditservice: http://localhost:8083
orderservice: http://localhost:8084
paymentservice: http://localhost:8085
paypalservice: http://localhost:8086
productservice: http://localhost:8087
shippingservice: http://localhost:8088