server:
  port: 8086
spring:  
  application:
    name: paypal-service
accountservice: http://localhost:8081
bankaccountservice: http://localhost:8082
creditservice: http://localhost:8083
orderservice: http://localhost:8084
paymentservice: http://localhost:8085
paypalservice: http://localhost:8086
productservice: http://localhost:8087
shippingservice: http://localhost:8088