apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-service-deployment
  labels:
    app: credit
spec:
  selector:
    matchLabels:
      app: credit
  replicas: 1
  template:
    metadata:
      labels:
        app: credit
    spec:
      containers:
        - name: credit
          image: webper2606/swa-project2:credit-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: ACCOUNT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: credit-config
                  key: account_service
            - name: BANK_ACCOUNT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: credit-config
                  key: bank_account_service
            - name: CREDIT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: credit-config
                  key: credit_service
            - name: ORDER_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: credit-config
                  key: order_service
            - name: PAYMENT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: credit-config
                  key: payment_service
            - name: PAYPAL_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: credit-config
                  key: paypal_service
            - name: PRODUCT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: credit-config
                  key: product_service
            - name: SHIPPING_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: credit-config
                  key: shipping_service

---
kind: Service
apiVersion: v1
metadata:
  name: credit-service
spec:
  selector:
    app: credit
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: credit-config
data:
  account_service: account-service
  bank_account_service: bank-account-service
  credit_service: credit-service
  order_service: order-service
  payment_service: payment-service
  paypal_service: paypal-service
  product_service: product-service
  shipping_service: shipping-service
