server:
  port: 8083
spring:  
  application:
    name: credit-service
account_service: http://localhost:8081
bank_account_service: http://localhost:8082
credit_service: http://localhost:8083
order_service: http://localhost:8084
payment_service: http://localhost:8085
paypal_service: http://localhost:8086
product_service: http://localhost:8087
shipping_service: http://localhost:8088